version: '3.8'

services:
  cawcat-app:
    image: clifford-faclifford-yzÄ«nvqi-backend:latest
    container_name: cawcat_app
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cawcat.rule=Host(`app.cavocat.fr`)"
      - "traefik.http.routers.cawcat.entrypoints=websecure"
      - "traefik.http.routers.cawcat.tls=true"
      - "traefik.http.routers.cawcat.tls.certresolver=letsencrypt"
      - "traefik.http.services.cawcat.loadbalancer.server.port=3000"
      - "traefik.docker.network=dokploy-network"
    environment:
      - NODE_ENV=production

networks:
  dokploy-network:
    external: true
